spring.application.name=v0.1
# Puerto en el que la aplicacion de Spring Boot escuchara las solicitudes HTTP
server.port=4000
# Configuramos la URL de conexion para la base de datos MySQL
# Desactiva el uso de SSL para la conexion
spring.datasource.url=jdbc:mysql://localhost:3306/adopciones_db?useSSL=false
# Nombre de usuario y password para conectarse a la base de datos
spring.datasource.username=root
spring.datasource.password=edwin22
# Hibernate no realizara ninguna accion sobre el esquema de la base de datos
# no creara ni modificara tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
# Configuramos el dialecto de la base de datos que Hibernate utilizara
# para interactuar con MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Definimos la clase del controlador JDBC que Spring Boot utilizara para conectarse
# a la base de datos MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=c3VwZXIgYXBwIHNicmUgYWRvcGNpb25lcyB2aXZhbiBsb3MgYW5pbWFsaXRvcwo=
jwt.expiration=86400000

# CORS para React (AJUSTAR!!!!)
cors.allowed-origin=http://localhost:5173

spring.security.user.name=disabled